version: '3.8'

services:
  # Template for user containers
  ssh-container-template:
    build: .
    restart: unless-stopped
    volumes:
      - ./shared:/shared:ro  # Read-only shared resources
    environment:
      - USERS=${USERS:-""}
    healthcheck:
      test: ["CMD-SHELL", "nc -z localhost 22 || exit 1"]
      interval: 10s
      timeout: 3s
      retries: 5
      start_period: 5s
    networks:
      - user-network

volumes: {}

networks:
  user-network:
    driver: bridge